#pragma once
#include "can/CANOpenDevice.hpp"

#define VCU_NODE_ID 5

#define CAN_TASK_PRIORITY (TASK_PRIORITY_DEFAULT + 3)
#define INVERTER_TASK_PRIORITY (TASK_PRIORITY_DEFAULT + 2)
#define TRACTIVE_SYSTEM_TASK_PRIORITY (TASK_PRIORITY_DEFAULT + 2)
#define BATTERY_TASK_PRIORITY (TASK_PRIORITY_DEFAULT + 1)
#define CANOPEN_HOST_TASK_PRIORITY (TASK_PRIORITY_DEFAULT)

#define INVERTER_SEND_PERIOD 500
#define BMS_NMT_SEND_PERIOD 500

#define INVERTER_TPDO1 0x180
#define INVERTER_TPDO2 0x280
#define INVERTER_TPDO3 0x380
#define INVERTER_TPDO4 0x480

#define INVERTER_RPDO1 0x200

#define INVERTER_CONTROLWORD_INDEX 0x6040
#define INVERTER_CONTROLWORD_SUBINDEX 0x00

#define INVERTER_CW_DISABLE_PWM 6
#define INVERTER_CW_ENABLE_PWM 15

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Number between 0 and 1000
#define INVERTER_MAXMIMUM_TORQUE_REQUEST 900
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#define INVERTER_MINIMUM_TORQUE_REQUEST -200

#define INVERTER_NM_PER_UNIT 0.14

#define RPM_TO_RADS_FACTOR 0.10472

#define ADC_RESOLUTION 4096

// TODO: These could go in dynamic configuration.
#define CONTACTOR_CLOSE_TIMEOUT 10000 // ms, the maximum time to wait for contactors to close
#define APPS_TIMEOUT 300              // ms, maximum APPS implausibility length
#define BRAKE_TIMEOUT 300

#define APPS_PLAUSIBILITY_FRACTION 0.3
#define BRAKE_PLAUSIBILITY_FRACTION 0.3

#define BRAKEPRESSURE1_AVERAGE_START 365
#define BRAKEPRESSURE1_RANGE 3731

#define BRAKEPRESSURE1_MIN_THRESHOLD 550

#define BRAKEPRESSURE2_AVERAGE_START 220
#define BRAKEPRESSURE2_RANGE 1828

#define BRAKEPRESSURE1_CHANNEL 2
#define BRAKEPRESSURE2_CHANNEL 3

#define BRAKEPRESSURE1_LOW_ADC 200
#define BRAKEPRESSURE1_HIGH_ADC 3500

#define BRAKEPRESSURE2_LOW_ADC 100
#define BRAKEPRESSURE2_HIGH_ADC 3500

#define BUZZER_LENGTH 1500 // ms, how long the buzzer buzzes

#define INV_CW_INDEX 0x6040
#define INV_CW_SUBINDEX 0x00

#define ADC_FREQUENCY 1000000

#define APPS1_CHANNEL 0
#define APPS1_ANGLE_OFFSET 174.4
#define APPS1_ANGLE_RANGE 12.6

#define APPS2_CHANNEL 1
#define APPS2_ANGLE_OFFSET 271
#define APPS2_ANGLE_RANGE -14.6

#define APPS_IGNORE_FRACTION 0.1

#define APPS_LOW_VOLTAGE 0.16
#define APPS_HIGH_VOLTAGE 1.64

#define APPS_MAX_VOLTAGE 1.8
#define APPS_MAX_ANGLE 360
#define APPS_START_FRACTION 0.1
#define APPS_END_FRACTION 0.9

#define APPS_USE_SMOOTH true
#define APPS_WINDOW 6

#define MAX_APPS_REGEN_FRACTION 0.15
#define MAX_ACCELERATION_REGEN_FRACTION 1.0
#define BRAKE_REGEN_SENSITIVITY 1.0

#define HARD_BRAKE_APPS_LIMIT 0.25
#define HARD_BRAKE_APPS_RELEASE 0.05

#define MAX_BATTERY_VOLTAGE 350

#define REGEN_MIN_RPM 250
#define REGEN_DERATE_RPM 500